// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuuclfppxgftyjdwpglv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1dWNsZnBweGdmdHlqZHdwZ2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDU0MzMsImV4cCI6MjA3MzUyMTQzM30.-M1Fq-Gp22Z5U79jPoWwfJIjSU7m-CuzzcLgOzASngg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});